{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "khook.fullname" . }}-metrics
  namespace: {{ include "khook.namespace" . }}
  labels:
    {{- include "khook.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "khook.selectorLabels" . | nindent 4 }}
{{- end }}