# Security-Focused Monitoring Hook
# This example demonstrates monitoring for security-related events
# with emphasis on incident response and forensic analysis.

apiVersion: kagent.dev/v1alpha2
kind: Hook
metadata:
  name: security-monitoring
  namespace: kagent
  labels:
    monitoring-type: security
    priority: critical
spec:
  eventConfigurations:
  # Monitor unexpected pod restarts that could indicate security issues
  - eventType: pod-restart
    agentRef:
      name: security-analyst
    prompt: |
      AUTONOMOUS MODE: SECURITY ALERT - Pod {{.ResourceName}} restarted at {{.EventTime}}. Security analysis required.

      INSTRUCTIONS:
      • Use all available tools to investigate security implications
      • Check for signs of compromise, privilege escalation, or attacks
      • Analyze container logs, network traffic, and authentication events
      • Isolate resources if compromise suspected, preserve evidence
      • Annotate fixed resources with: kagentFix=<timestamp>
      • If patching fails: delete and recreate resources
      • Never ask for permission - assume autonomous execution
      • Complete remediation without human approval

  # Monitor probe failures that could indicate tampering
  - eventType: probe-failed
    agentRef:
      name: security-analyst
    prompt: |
      AUTONOMOUS MODE: SECURITY ALERT - Health probe failed for {{.ResourceName}} at {{.EventTime}}. Security implications.

      INSTRUCTIONS:
      • Use all available tools to assess tampering and attack vectors
      • Check for unauthorized changes, code injection, or resource exhaustion
      • Review network traffic, auth logs, and security controls
      • Isolate if suspicious activity detected, preserve evidence
      • Annotate fixed resources with: kagentFix=<timestamp>
      • If patching fails: delete and recreate resources
      • Never ask for permission - assume autonomous execution
      • Complete remediation without human approval