{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "khook.fullname" . }}-manager-role
  labels:
    {{- include "khook.labels" . | nindent 4 }}
rules:
# Hook CRD permissions
- apiGroups:
  - kagent.dev
  resources:
  - hooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kagent.dev
  resources:
  - hooks/finalizers
  verbs:
  - update
- apiGroups:
  - kagent.dev
  resources:
  - hooks/status
  verbs:
  - get
  - patch
  - update
# Event watching permissions
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - patch
# Events API v1 (events.k8s.io)
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - get
  - list
  - watch
# Pod information for event context
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
# Node information for event context
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
# Namespace information
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "khook.fullname" . }}-manager-rolebinding
  labels:
    {{- include "khook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "khook.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "khook.serviceAccountName" . }}
  namespace: {{ include "khook.namespace" . }}
---
{{- if .Values.controller.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "khook.fullname" . }}-leader-election-role
  namespace: {{ include "khook.namespace" . }}
  labels:
    {{- include "khook.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "khook.fullname" . }}-leader-election-rolebinding
  namespace: {{ include "khook.namespace" . }}
  labels:
    {{- include "khook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "khook.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "khook.serviceAccountName" . }}
  namespace: {{ include "khook.namespace" . }}
{{- end }}
{{- end }}