apiVersion: v2
name: khook
description: khook - a Kubernetes hook controller that integrates with Kagent (A2A)
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/kagent-dev/khook
sources:
- https://github.com/kagent-dev/khook
maintainers:
- name: Kagent Team
  email: support@kagent.dev
keywords:
- kubernetes
- controller
- automation
- events
- kagent
- hooks